quarkus.http.port=${HTTP_PORT:8081}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:11155636}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:8845}/${DB_NAME:dbutil}

quarkus.datasource.jdbc.max-size=${DB_POOL_MAX_SIZE:10}

util.tenant-id=${UTIL_TENANT_ID:local}
util.api-version=${UTIL_API_VERSION:dev}
util.database-name=${DB_NAME:dbutil}

tiendanube.store-id=${TIENDANUBE_STORE_ID:8049321}
tiendanube.token=${TIENDANUBE_TOKEN:54d1328436b22cb80c1c89f544b3f7fa86d3472a}

tiendanube.app-id=${TIENDANUBE_APP_ID:}
tiendanube.client-secret=${TIENDANUBE_CLIENT_SECRET:}
tiendanube.api-url=https://api.tiendanube.com/2025-03